Add macOS alpha release workflow (#1391)
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210800425272850?focus=true

Description:
This change adds macos_alpha_release.yml workflow that builds and publishes
Alpha release to Sparkle and TestFlight.
Additionally, the regular app gets a Debug Menu option to get the Alpha build.
This change doesn’t cover enabling the alpha workflow in main branch.

diff --git a/.github/workflows/macos_build_appstore.yml b/.github/workflows/macos_build_appstore.yml
--- a/.github/workflows/macos_build_appstore.yml
+++ b/.github/workflows/macos_build_appstore.yml
@@ -30,12 +30,21 @@ on:
         type: string
       asana-task-url:
         description: "Asana release task URL"
-        required: true
+        required: false
         type: string
       branch:
         description: "Branch name"
         required: false
         type: string
+      build-number-override:
+        description: "Override build number (for Alpha builds)"
+        required: false
+        type: string
+      skip-notify:
+        description: "Skip Mattermost notification"
+        required: false
+        default: false
+        type: boolean
     secrets:
       SSH_PRIVATE_KEY_FASTLANE_MATCH:
         required: true
@@ -101,7 +110,7 @@ jobs:
       env:
         is-official-release: ${{ (env.destination == 'appstore' || env.destination == 'testflight') && (startsWith(env.branch, 'release') || startsWith(env.branch, 'hotfix')) }}
       run: |
-        if [[ "${{ env.is-official-release }}" == "true" ]]; then
+        if [[ "${{ env.is-official-release }}" == "true" ]] || [[ "${{ env.destination }}" == "testflight_alpha" ]]; then
           upload_to=s3
           echo "upload-to=${upload_to}" >> $GITHUB_OUTPUT
           echo "upload-to=${upload_to}" >> $GITHUB_ENV
@@ -109,6 +118,12 @@ jobs:
 
     - name: Select Xcode
       uses: ./.github/actions/select-xcode-version
+
+    - name: Override build number for Alpha release
+      if: ${{ env.destination == 'testflight_alpha' && inputs.build-number-override != '' }}
+      run: |
+        echo "Overriding build number to ${{ inputs.build-number-override }}"
+        echo "CURRENT_PROJECT_VERSION = ${{ inputs.build-number-override }}" > Configuration/BuildNumber.xcconfig
 
     - name: Archive and Upload the App
       env:
@@ -135,10 +150,11 @@ jobs:
         bundle exec fastlane release_${{ env.destination }}
         dsym_path="${{ github.workspace }}/macOS/${app_dsym_name}.app.dSYM.zip"
         mv -f "${{ github.workspace }}/macOS/${app_bundle_name}.app.dSYM.zip" "${dsym_path}"
-        version="$(cut -d ' ' -f 3 < Configuration/Version.xcconfig)"
-        build_number="$(cut -d ' ' -f 3 < Configuration/BuildNumber.xcconfig)"
+        version="$(cut -d ' ' -f 3 < Configuration/Version.xcconfig | tr -d '\n')"
+        build_number="$(cut -d ' ' -f 3 < Configuration/BuildNumber.xcconfig | tr -d '\n')"
         echo "dsym-path=${dsym_path}" >> $GITHUB_ENV
         echo "app-version=${version}.${build_number}" >> $GITHUB_ENV
+        echo "app-dsym-name=${app_dsym_name}" >> $GITHUB_ENV
 
     - name: Upload dSYMs artifact
       uses: actions/upload-artifact@v4
@@ -153,7 +169,7 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
-        DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.MACOS_DSYM_BUCKET_PREFIX }}/DuckDuckGo-AppStore-${{ env.app-version }}-dSYM.zip
+        DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.MACOS_DSYM_BUCKET_PREFIX }}/${{ env.app-dsym-name }}-${{ env.app-version }}-dSYM.zip
       run: |
         echo "dsym-s3-path=${DSYM_S3_PATH}" >> $GITHUB_OUTPUT
         aws s3 cp ${{ env.dsym-path }} ${{ env.DSYM_S3_PATH }}
@@ -179,7 +195,9 @@ jobs:
         DESTINATION: ${{ env.destination }}
         PLATFORM: macOS
       run: |
-        bundle exec fastlane run mattermost_send_message \
-          mattermost_webhook_url:${{ secrets.MM_WEBHOOK_URL }} \
-          github_handle:${{ github.actor }} \
-          template_name:$([[ "${{ job.status }}" == "success" ]] && echo "public-release-complete" || echo "public-release-failed")
+        if [[ "${{ inputs.skip-notify }}" == "false" ]]; then
+          bundle exec fastlane run mattermost_send_message \
+            mattermost_webhook_url:${{ secrets.MM_WEBHOOK_URL }} \
+            github_handle:${{ github.actor }} \
+            template_name:$([[ "${{ job.status }}" == "success" ]] && echo "public-release-complete" || echo "public-release-failed")
+        fi
