Update macOS code freeze for testing

diff --git a/.github/workflows/macos_code_freeze.yml b/.github/workflows/macos_code_freeze.yml
--- a/.github/workflows/macos_code_freeze.yml
+++ b/.github/workflows/macos_code_freeze.yml
@@ -18,128 +18,139 @@ concurrency:
 
 jobs:
 
-  create_release_branch:
+  # create_release_branch:
 
-    name: Create Release Branch
+  #   name: Create Release Branch
 
-    runs-on: macos-15-xlarge
-    timeout-minutes: 10
+  #   runs-on: macos-15-xlarge
+  #   timeout-minutes: 10
 
-    outputs:
-      release_branch_name: ${{ steps.make_release_branch.outputs.release_branch_name }}
-      asana_task_id: ${{ steps.make_release_branch.outputs.asana_task_id }}
-      asana_task_url: ${{ steps.make_release_branch.outputs.asana_task_url }}
+  #   outputs:
+  #     release_branch_name: ${{ steps.make_release_branch.outputs.release_branch_name }}
+  #     asana_task_id: ${{ steps.make_release_branch.outputs.asana_task_id }}
+  #     asana_task_url: ${{ steps.make_release_branch.outputs.asana_task_url }}
 
-    steps:
-      - name: Check out the code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Fetch all history and tags in order to extract Asana task URLs from git log
-          submodules: recursive
+  #   steps:
+  #     - name: Check out the code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # Fetch all history and tags in order to extract Asana task URLs from git log
+  #         submodules: recursive
 
-      - name: Assert main branch
-        run: |
-          if [ "${{ github.ref_name }}" != "main" ]; then
-            echo "👎 Not the main branch"
-            exit 1
-          fi
+  #     - name: Assert main branch
+  #       run: |
+  #         if [ "${{ github.ref_name }}" != "main" ]; then
+  #           echo "👎 Not the main branch"
+  #           exit 1
+  #         fi
 
-      - name: Setup Ruby and dependencies
-        uses: ./.github/actions/setup-ruby
-        with:
-          working-directory: macOS
-          cache-key-prefix: macos-ruby
+  #     - name: Setup Ruby and dependencies
+  #       uses: ./.github/actions/setup-ruby
+  #       with:
+  #         working-directory: macOS
+  #         cache-key-prefix: macos-ruby
 
-      - name: Make release branch
-        id: make_release_branch
-        env:
-          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
-          GITHUB_TOKEN: ${{ github.token }}
-          DBP_API_AUTH_TOKEN: ${{ secrets.DBP_API_AUTH_TOKEN }}
-        run: |
-          bundle exec fastlane run start_new_release \
-            platform:"macos" \
-            version:"${{ inputs.version }}" \
-            github_handle:"${{ github.actor }}" \
-            target_section_id:"${{ vars.MACOS_APP_BOARD_VALIDATION_SECTION_ID }}"
+  #     - name: Make release branch
+  #       id: make_release_branch
+  #       env:
+  #         ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+  #         GITHUB_TOKEN: ${{ github.token }}
+  #         DBP_API_AUTH_TOKEN: ${{ secrets.DBP_API_AUTH_TOKEN }}
+  #       run: |
+  #         bundle exec fastlane run start_new_release \
+  #           platform:"macos" \
+  #           version:"${{ inputs.version }}" \
+  #           github_handle:"${{ github.actor }}" \
+  #           target_section_id:"${{ vars.MACOS_APP_BOARD_VALIDATION_SECTION_ID }}"
 
-  run_tests:
+  # run_tests:
 
-    name: Run Tests
+  #   name: Run Tests
 
-    needs: create_release_branch
-    uses: ./.github/workflows/macos_pr_checks.yml
-    with:
-      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
-    secrets: inherit
+  #   needs: create_release_branch
+  #   uses: ./.github/workflows/macos_pr_checks.yml
+  #   with:
+  #     branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
+  #   secrets: inherit
 
-  increment_build_number:
+  # increment_build_number:
 
-    name: Increment Build Number
+  #   name: Increment Build Number
 
-    needs: [ create_release_branch, run_tests ]
-    runs-on: macos-15-xlarge
-    timeout-minutes: 10
+  #   needs: [ create_release_branch, run_tests ]
+  #   runs-on: macos-15-xlarge
+  #   timeout-minutes: 10
 
-    outputs:
-      commit_sha: ${{ steps.increment-build-number.outputs.commit_sha }}
+  #   outputs:
+  #     commit_sha: ${{ steps.increment-build-number.outputs.commit_sha }}
 
-    steps:
+  #   steps:
 
-      - name: Check out the code
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
-          ref: ${{ needs.create_release_branch.outputs.release_branch_name }}
+  #     - name: Check out the code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #         ref: ${{ needs.create_release_branch.outputs.release_branch_name }}
 
-      - name: Setup Ruby and dependencies
-        uses: ./.github/actions/setup-ruby
-        with:
-          working-directory: macOS
-          cache-key-prefix: macos-ruby
+  #     - name: Setup Ruby and dependencies
+  #       uses: ./.github/actions/setup-ruby
+  #       with:
+  #         working-directory: macOS
+  #         cache-key-prefix: macos-ruby
 
-      - name: Increment build number
-        id: increment-build-number
-        env:
-          APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
-          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
-          APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
-          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
-          GITHUB_TOKEN: ${{ github.token }}
-        run: |
-          bundle exec fastlane run bump_build_number platform:macos
+  #     - name: Increment build number
+  #       id: increment-build-number
+  #       env:
+  #         APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
+  #         APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
+  #         APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
+  #         ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+  #         GITHUB_TOKEN: ${{ github.token }}
+  #       run: |
+  #         bundle exec fastlane run bump_build_number platform:macos
 
-  prepare_release:
-    name: Prepare Release
-    needs: [ create_release_branch, increment_build_number ]
-    uses: ./.github/workflows/macos_release.yml
-    with:
-      asana-task-url: ${{ needs.create_release_branch.outputs.asana_task_url }}
-      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
-      commit-sha: ${{ needs.increment_build_number.outputs.commit_sha }}
-    secrets: inherit
+  # prepare_release:
+  #   name: Prepare Release
+  #   needs: [ create_release_branch, increment_build_number ]
+  #   uses: ./.github/workflows/macos_release.yml
+  #   with:
+  #     asana-task-url: ${{ needs.create_release_branch.outputs.asana_task_url }}
+  #     branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
+  #     commit-sha: ${{ needs.increment_build_number.outputs.commit_sha }}
+  #   secrets: inherit
 
-  tag_and_merge:
-    name: Tag and Merge Branch
-    needs: [ create_release_branch, increment_build_number, prepare_release ]
-    uses: ./.github/workflows/macos_tag_release.yml
-    with:
-      asana-task-url: ${{ needs.create_release_branch.outputs.asana_task_url }}
-      base-branch: ${{ github.ref_name }}
-      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
-      commit-sha: ${{ needs.increment_build_number.outputs.commit_sha }}
-      prerelease: true
-    secrets: inherit
+  # tag_and_merge:
+  #   name: Tag and Merge Branch
+  #   needs: [ create_release_branch, increment_build_number, prepare_release ]
+  #   uses: ./.github/workflows/macos_tag_release.yml
+  #   with:
+  #     asana-task-url: ${{ needs.create_release_branch.outputs.asana_task_url }}
+  #     base-branch: ${{ github.ref_name }}
+  #     branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
+  #     commit-sha: ${{ needs.increment_build_number.outputs.commit_sha }}
+  #     prerelease: true
+  #   secrets: inherit
+
+  # report_failure:
+  #   name: Report Failure
+  #   if: failure()
+  #   needs: [ create_release_branch, increment_build_number, tag_and_merge ]
+  #   uses: ./.github/workflows/report_failed_release_workflow.yml
+  #   with:
+  #     asana-task-id: ${{ needs.create_release_branch.outputs.asana_task_id }}
+  #     branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
+  #     commit-sha: ${{ needs.increment_build_number.outputs.commit_sha }}
+  #     workflow-name: "Code Freeze"
+  #     working-directory: macOS
+  #   secrets: inherit
 
   report_failure:
     name: Report Failure
-    if: failure()
-    needs: [ create_release_branch, increment_build_number, tag_and_merge ]
     uses: ./.github/workflows/report_failed_release_workflow.yml
     with:
-      asana-task-id: ${{ needs.create_release_branch.outputs.asana_task_id }}
-      branch: ${{ needs.create_release_branch.outputs.release_branch_name }}
-      commit-sha: ${{ needs.increment_build_number.outputs.commit_sha }}
-      workflow-name: "Code Freeze"
+      asana-task-id: "1211112466075936"
+      branch: "dominik/report-workflow-failure"
+      commit-sha: "b642b649e165ac3a8c8a380de448ddaa99fb558d"
+      workflow-name: "code freeze"
       working-directory: macOS
     secrets: inherit
