Replace working-directory with platform

diff --git a/.github/workflows/report_failed_release_workflow.yml b/.github/workflows/report_failed_release_workflow.yml
--- a/.github/workflows/report_failed_release_workflow.yml
+++ b/.github/workflows/report_failed_release_workflow.yml
@@ -15,12 +15,12 @@ on:
         description: "Commit SHA"
         required: false
         type: string
-      workflow-name:
-        description: "Workflow name"
+      platform:
+        description: "Platform (ios/macos)"
         required: true
         type: string
-      working-directory:
-        description: "Working directory (iOS/macOS)"
+      workflow-name:
+        description: "Workflow name"
         required: true
         type: string
   workflow_call:
@@ -37,12 +37,12 @@ on:
         description: "Commit SHA"
         required: false
         type: string
-      workflow-name:
-        description: "Workflow name"
+      platform:
+        description: "Platform (ios/macos)"
         required: true
         type: string
-      working-directory:
-        description: "Working directory (iOS/macOS)"
+      workflow-name:
+        description: "Workflow name"
         required: true
         type: string
 
@@ -54,6 +54,22 @@ jobs:
 
     steps:
 
+      - name: Set working directory
+        id: set-working-directory
+        run: |
+          case "${{ inputs.platform }}" in
+            ios)
+              echo "working_directory=iOS" >> $GITHUB_OUTPUT
+              ;;
+            macos)
+              echo "working_directory=macOS" >> $GITHUB_OUTPUT
+              ;;
+            *)
+              echo "::error::Invalid platform '${{ inputs.platform }}'."
+              exit 1
+            ;;
+          esac
+
       - name: Check out the code
         uses: actions/checkout@v4
         with:
@@ -63,16 +79,17 @@ jobs:
       - name: Setup Ruby and dependencies
         uses: ./.github/actions/setup-ruby
         with:
-          working-directory: ${{ inputs.working-directory }}
-          cache-key-prefix: macos-ruby
+          working-directory: ${{ steps.set-working-directory.outputs.working_directory }}
+          cache-key-prefix: ${{ inputs.platform }}-ruby
 
       - name: Report failed workflow
-        working-directory: ${{ inputs.working-directory }}
+        working-directory: ${{ steps.set-working-directory.outputs.working_directory }}
         env:
           ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
           GITHUB_TOKEN: ${{ github.token }}
         run: |
           bundle exec fastlane run asana_report_failed_workflow \
+            platform:"${{ inputs.platform }}" \
             branch:"${{ inputs.branch }}" \
             commit_sha:"${{ inputs.commit-sha }}" \
             github_handle:"${{ github.actor }}" \
